### ISSUE TITLE
Malware that must be run as a service

### ISSUE THREAD

**Issue by malwarefrank** [MBCProject/mbc-markdown#15]
I am analyzing [a piece of malware](https://www.virustotal.com/gui/file/304f533ce9ea4a9ee5c19bc81c49838857c63469e26023f330823c3240ee4e03/detection) that must be run as a service.  It assumes that it has already been set up as a service by some other program or manually, so does not contain code itself to create a new service or modify existing.

This can cause problems for behavioral analysis, such as Cuckoo Sandbox which [does not support a Service analysis package](https://cuckoo.readthedocs.io/en/latest/usage/packages/), and debugging since [debugging services is not straightforward](https://docs.microsoft.com/en-us/dotnet/framework/windows-services/how-to-debug-windows-service-applications).

The closest behavior I could find is Execution Guardrails (E1480).  However, I believe this requires adding a new Method.  I do not know if it would be better to be specific (e.g. Must run as service) or more general (e.g. Must be run in a specific way) or something in between (e.g. Must be run by specific Windows process).

**Comment by williballenthin** [comment]
related capa rule: https://github.com/fireeye/capa-rules/blob/master/executable/pe/run-as-a-service.yml

**Comment by dzbeck** [comment]
What do you think about defining these two methods?

Name: “Runs as Service” 
ID: E1480.m07
Description: The malware must be run as a service, which can make behavioral analysis and debugging more difficult. The service may be set up by the malware. Alternatively, the malware may not contain any code to create a new service or modify an existing service, in which case, the service may be set up by another program or manually.

Name: “Runs as Service – Windows Process”
ID: E1480.m08
Description: The malware must be run as a service, which can make behavioral analysis and debugging more difficult. The service may be set up by the malware. Alternatively, the malware may not contain any code to create a new service or modify an existing service, in which case, the service may be set up by another program or manually. Under this method, the malware is be run by a specific Windows process.

Any references to add? Or changes/additions to descriptions?

**Comment by dzbeck** [comment]
> related capa rule: https://github.com/fireeye/capa-rules/blob/master/executable/pe/run-as-a-service.yml

@williballenthin - thanks! We're working on more capa mappings and will include this one.

**Comment by malwarefrank** [comment]
Hmm... @dzbeck I think your "Runs as Service" description will work.  The "Runs as Service - Windows Process" feels duplicative.

You can reference the malware sample I linked to on VT.  This also seems to be a good description of the problem and some analysis recommendations: https://reverseengineering.stackexchange.com/questions/2019/debugging-malware-that-will-only-run-as-a-service

**Comment by dzbeck** [comment]
Thanks @malwarefrank. Makes sense - added "Runs as Service" method and include the ref.
