### ISSUE TITLE
New method: Force Lazy Writing

### ISSUE THREAD

**Issue by malwarefrank** [MBCProject/mbc-markdown#18]
I would like to propose "Force Lazy Writing" as a new Method to be placed under Defense Evasion - Disable Security Tools.

Description: Some operating systems will sometimes use a form of "lazy writing" for disk I/O, which may obscure the true provenance of the write operation.  This method occurs when code intentionally forces the operating system to perform a lazy writing operation.  For example, in Windows, a file may be opened, memory mapped, and closed, but the memory map will still exist and can be written to, which will cause a lazy write that looks like it is coming from the System process.

A [recent VBConf presentation](https://vblocalhost.com/conference/presentations/stealthy-wastedlocker-eluding-behaviour-blockers-but-not-only/) presented the idea as seen implemented by WastedLocker ransomware.

**Comment by dzbeck** [comment]
added - thanks @malwarefrank !
