### ISSUE TITLE
Add MBC micro-behavior for thread resume

### ISSUE THREAD

**Issue by 0x534a** [MBCProject/mbc-markdown#21]
While expanding the capa rule set, I noticed that there is currently no micro-behavior for resuming a thread. Therefore, I suggest to add this micro-behavior to MBC. Malware typically resumes a thread in order to execute previously injected code (e.g. in the course of the [process hollowing technique](https://attack.mitre.org/techniques/T1055/012/)).

This micro-behavior should fit to the [Process Micro-objective](https://github.com/MBCProject/mbc-markdown/tree/master/micro-behaviors/process) where similar behavior like creating or terminating a thread is already located.

In the same turn, suspending a thread can also be added analogously as micro-behaviour.

**Comment by dzbeck** [comment]
@0x534a thanks for the suggestion - added!
