### ISSUE TITLE
B0025 and E1480 duplicative

### ISSUE THREAD

**Issue by malwarefrank** [MBCProject/mbc-markdown#23]
As they are currently worded, [B0025 - Conditional Execution](https://github.com/MBCProject/mbc-markdown/blob/master/execution/conditional-execute.md) and [E1480 - Execution Guardrails](https://github.com/MBCProject/mbc-markdown/blob/master/anti-behavioral-analysis/execution-guardrails.md) sound the same.

**Comment by dzbeck** [comment]
Good find - thanks. These have been combined under B0025 - Conditional Execution.
