### ISSUE TITLE
Server and client terminology is confusing

### ISSUE THREAD

**Issue by malwarefrank** [MBCProject/mbc-markdown#25]
Recommending moving away from using terms "server" and "client" in [Command and Control](https://github.com/MBCProject/mbc-markdown/blob/master/command-and-control/command-control-comm.md) as their definitions have become muddied when referring to malware, and RATs in particular.  For example, some people call the side that the attacker controls the client (from the point of view of the attacker) while others refer to it as the server (from the point of view of the victim who sees their endpoint reaching out to a "server").

I recommend instead using the terms that have less confusion surrounding their use, such as "implant" and "controller", and explicitly defining them as victim-side and attacker-side, respectively.  This terminology works for not only RATs where the implant initiates contact with the controller, but also for Webshells where the controller initiates contact with the implant.

**Comment by malwarefrank** [comment]
I can create a PR if this makes sense

**Comment by dzbeck** [comment]
great recommendation - a PR would be appreciated- thanks!
