### ISSUE TITLE
New C2 Methods

### ISSUE THREAD

**Issue by malwarefrank** [MBCProject/mbc-markdown#26]
Add a new Methods to [Command and Control](https://github.com/MBCProject/mbc-markdown/blob/master/command-and-control/command-control-comm.md):

- Execute file - Execute/run/open the file, that may already exist or not, using default operating system functionality, optionally with provided command-line arguments.
- Start interactive shell - Start an interactive shell using a built-in (e.g. cmd.exe, PowerShell, bash) program.
- Execute shell command - Execute/run the given command using a built-in (e.g. cmd.exe, PowerShell, bash) program.
- Directory listing - Controller requests a directory listing from the implant, optionally from a given path, optionally recursive.
- File search - Controller requests the implant to search for a given filename pattern, often a [glob](https://en.wikipedia.org/wiki/Glob_(programming)).
- Authenticate - Implant may authenticate itself to the controller, controller may authenticate itself to implant, or both.  This is often at or near the start of communication.  Examples include but are not limited to a simple shared secret (e.g. password), challenge-response with symmetric encryption, or challenge-response with asymmetric encryption.

**Comment by malwarefrank** [comment]
I can create a PR if this looks good

**Comment by dzbeck** [comment]
looks good - a PR would be great - thanks!
