### ISSUE TITLE
Ransom note

### ISSUE THREAD

**Issue by malwarefrank** [MBCProject/mbc-markdown#28]
add a new Method to [Data Encrypted for Impact](https://github.com/MBCProject/mbc-markdown/blob/master/impact/encrypt-impact.md):  Random note

**Comment by malwarefrank** [comment]
Ransomware must display a ransom note, and ransom notes are sometimes used to link instances of ransomware even when the code, or anti-analysis techniques, change.

**Comment by dzbeck** [comment]
good suggestion. Method added.
