### ISSUE TITLE
Explicit module loading

### ISSUE THREAD

**Issue by malwarefrank** [MBCProject/mbc-markdown#3]
I would like to propose a new Execution technique.

Some malware will load executable, from disk or elsewhere, not by using standard operating system (OS) mechanisms but by explicitly or manually parse the other file's PE header and section information and setting up the memory segments manually instead of relying on the OS to do so.  This has the effect of loading the other file's code into the current executable's memory space in a way that it can then be executed or called into.

An example is how the "maindll.dll" mentioned here:
    https://citizenlab.ca/2016/04/between-hong-kong-and-burma/
loads the "dll2.xor" file.

**Comment by dzbeck** [comment]
This seems similar to either Process Injection (https://github.com/MBCProject/mbc-markdown/blob/master/defense-evasion/process-inject.md) or Process Hollowing (https://github.com/MBCProject/mbc-markdown/blob/master/defense-evasion/process-hollow.md). If neither of those is a good fit, could you suggest a name and description?

**Comment by malwarefrank** [comment]
Process Injection might make sense, since the ATT&CK description mentions reflective loading, which is similar to what I am seeing.  Although in the case of what maindll.dll mentioned above, it injects the external code into its own process.

If we adjust the definition of Process Injection to mean the taking of code external to a process and injecting it into that process outside of normal operating system loading functionality, then it could cover both the "malware injecting into legitimate process" scenario and the "custom loader taking code from somewhere external to it, optionally decoding it, and setting it up as code in its own process" scenario.  I also think this adds "Execution" to the list of objectives associated with Process Injection.

Thoughts?  If that sounds good, then I can make a PR to change the Process Injection page.

**Comment by dzbeck** [comment]
Expanding the Project Injection behavior description as you describe sounds good. Would the details be appropriate as a specific Method? The malware sample/family should be referenced in the Examples table. 

Regarding objective - is the executable loaded like this to avoid detection? If so, it would remain a behavior under the Defense Evasion objective. But if there is no anti-detection aspect - if it is simply a method of transparent execution - then I think adding it to the Execution objective makes sense.

I added some template content to process-inject.md and added a placeholder in the xample-malware directory (up007.md) to prepare for your update.

**Comment by malwarefrank** [comment]
Thanks.  I think it is done for Defense Evasion or Anti-Analysis.  It certainly can affect both detection and analysts.  I will take a look at the placeholder and add some wording to it.
