### ISSUE TITLE
Data flow evasion

### ISSUE THREAD

**Issue by malwarefrank** [MBCProject/mbc-markdown#32]
There are several anti-analysis techniques mentioned in the paper:

[Cavallaro, Lorenzo, Prateek Saxena, and R. Sekar. "On the limits of information flow techniques for malware analysis and containment." International conference on Detection of Intrusions and Malware, and Vulnerability Assessment. Springer, Berlin, Heidelberg, 2008.](http://www.seclab.cs.sunysb.edu/seclab/pubs/antitaint.pdf)

These are centered on taint analysis but more broadly affect data flow analysis techniques:

- **Control dependence** - propagating data via if-then-else clause instead of direct assignment.
- **Implicit flows** - propagating data via semantic relationships, for example one variable not changing its state could imply the state of another variable.
- **Arbitrary Memory Corruption** - propagating data by corrupting memory, for example overwriting a region of stack space where a file pointer is held.

I am not sure where these would fit in MBC.  They mainly affect static analysis, so maybe under Anti-Static Analysis as a new behavior and Methods?

**Comment by dzbeck** [comment]
Thanks @malwarefrank. Behavior and methods added.
