### ISSUE TITLE
HTML Tables inside Markdown

### ISSUE THREAD

**Issue by ikiril01** [MBCProject/mbc-markdown#35]
This is fairly minor, but it's possible to embed HTML tables inside of your markdown files. That means you can get away from having the "fake" table header that you need to create the summary markdown tables for each MBC entry.

So instead of:

|||
|---|---|
|**ID**|**B0027**|
|**Objective(s)**|[Defense Evasion](../defense-evasion)|
|**Related ATT&CK Technique**|None|

You'll get:

<table>
<tr>
    <td><b>ID</b></td>
    <td><b>B0027</b></td>
</tr>
<tr>
    <td><b>Objective(s)</b></td>
    <td><a href="../defense-evasion">Defense Evasion</a></td>
</tr>
<tr>
    <td><b>Related ATT&CK Techniques</b></td>
    <td>None</td>
</tr>
</table>

Here's what the HTML for this looks like:

```
<table>
<tr>
    <td><b>ID</b></td>
    <td><b>B0027</b></td>
</tr>
<tr>
    <td><b>Objective(s)</b></td>
    <td><a href="../defense-evasion">Defense Evasion</a></td>
</tr>
<tr>
    <td><b>Related ATT&CK Techniques</b></td>
    <td>None</td>
</tr>
</table>
```

**Comment by dzbeck** [comment]
Thanks - good idea. Will update as resources are available.
