### ISSUE TITLE
Anti-Capture

### ISSUE THREAD

**Issue by malwarefrank** [MBCProject/mbc-markdown#4]
Proposing adding a new Objective called Anti-Capture.

This would contain behaviors and methods that affect our ability to capture the malware from an infected system.  For example, the behavior described in #3, using multiple stages of loaders and an encoded payload.  If only the executables are captured, which is a common practice, then all or part of the true functionality of the malware is unable to be analyzed.

Other examples that affect capturing the "real" malware are
- in-memory-only payloads (e.g. RAT plugins received from the controller and never written to disk)
- downloaders
- encrypted payloads where the decryption key is stored external to the executable or never touches disk

**Comment by dzbeck** [comment]
How about adding "Capture Evasion" as a behavior under both the Anti-Behavioral Analysis and Anti-Static Analysis objectives (along the lines of the existing Memory Dump Evasion)? Methods under the behavior could include the examples you mention: in-memory-only payloads, downloaders, etc.

**Comment by dzbeck** [comment]
Please see "Capture Evasion" behavior under Anti-Behavioral Analysis.
