### ISSUE TITLE
Some Navigator links are pointing to wrong version

### ISSUE THREAD

**Issue by hfakar** [MBCProject/mbc-markdown#61]
In the navigator clicking B0013.001 Process Detection returns this: 
![image](https://user-images.githubusercontent.com/13640312/201037348-9863b398-b503-46b1-9b9e-9799d7697265.png)

**Comment by utkonos** [comment]
It looks like the reason for this is all the links in the SVG file that generates the navigator point to tag `v2.2` which does not always exist for each of the `.md` files that the links point to.

**Comment by dzbeck** [comment]
@hfakar - thanks for bringing this to our attention!
