### ISSUE TITLE
Opaque Predicate

### ISSUE THREAD

**Issue by utkonos** [MBCProject/mbc-markdown#65]
I'd like to propose two new methods:

# Opaque Predicate

```
Anti-Static Analysis::Executable Code Obfuscation::Opaque Predicate
```

When used as code obfuscation, there are two types: always jumps and never jumps. These can be used in different situations: skip over Dead Code Insertion, fake jump before executed code, fake dead end. The following screenshot shows all three of these situations together. The first opaque predicate at the top always jumps and creates a fake dead end on the right. The next opaque predicate never jumps and is followed by important code. The last one at the bottom always jumps over a stretch of Dead Code Insertion.

<img width="1476" alt="image" src="https://user-images.githubusercontent.com/2775739/202582140-4366b519-c8fb-4a83-92d0-bd3a04abe71d.png">

# Disruptive Opaque Predicate

```
Anti-Static Analysis::Disassembler Evasion::Disruptive Opaque Predicate
```

I am not working on a sample currently that has an example of this type of opaque predicate, but these are described in the following paper:
https://www.ndss-symposium.org/wp-content/uploads/2020/04/bar2020-23004-paper.pdf

The differentiation between the above to general categories of opaque predicate is that the former do not result in damage or incorrectness in the resulting disassembly. But the latter category results in totally incorrect disassembly somewhere after the opaque predicate.

**Comment by utkonos** [comment]
More info:

https://binary.ninja/2017/10/01/automated-opaque-predicate-removal.html

**Comment by utkonos** [comment]
The one I have named "Disruptive Opaque Predicate" may fit within `Anti-Static Analysis::Disassembler Evasion::Conditional Misdirection`. The definition would just need to be expanded a bit to cover both forms of conditional misdirection. The effect I think is the same: incorrect disassembly.

**Comment by dzbeck** [comment]
see PR #73
