### ISSUE TITLE
Anti-Emulation: Unimplemented Opcodes

### ISSUE THREAD

**Issue by utkonos** [MBCProject/mbc-markdown#68]
I propose an expansion of the definition and name of Undocumented Opcodes to:

"Undocumented/Unimplemented Opcodes"

"Use rare, undocumented, or unimplemented opcodes to block non-exhaustive emulators."

The Unicorn Engine at one point removed implementation for TIB:
https://github.com/unipacker/unicorn#:~:text=This%20fork%20provides,restores%20TIB%20functionality.

Here is a packer registering a exception handler, but that handler is never used:

<img width="590" alt="image" src="https://user-images.githubusercontent.com/2775739/202824556-c045a17d-7afe-46ee-8cb8-805c8f1b5e4a.png">

This is either Junk Code Insertion or Unimplemented Opcodes (I can't read the adversary's mind). This opcode is not rare nor is it undocumented. But this is a clearly known problem with a major emulator due to lack of implementation of the opcode. It is enough of a problem that an automated unpacker project has specifically forked the emulator to circumvent this issue.

**Comment by dzbeck** [comment]
@utkonos Thanks for the suggestion. The description has been updated as you suggested.
