### ISSUE TITLE
Github Discussions for MBC?

### ISSUE THREAD

**Issue by utkonos** [MBCProject/mbc-markdown#70]
I have a lot of thoughts about MBC and not all of them are specific enough to deserve an issue being opened in the repo. There is a new-ish feature on Github: "Discussions":

<img width="794" alt="image" src="https://user-images.githubusercontent.com/2775739/202925300-fc221514-6b41-4519-9df7-0aaecccf93d2.png">

Would enabling discussions on this repo be something that you all would be amenable to?

**Comment by dzbeck** [comment]
that sounds great! I'll try to do that now...
