### ISSUE TITLE
virtualized-code link is dead

### ISSUE THREAD

**Issue by cattrace** [MBCProject/mbc-markdown#9]
https://github.com/MBCProject/mbc-markdown/blob/master/anti-static-analysis/virtualized-code.md

 link is dead,  and  i found this, are they the same ting?

https://github.com/MBCProject/mbc-markdown/blob/3363844137c8d581ad0a4b813719c5527b7aba97/anti-static-analysis/exe-code-virtualize.md

**Comment by dzbeck** [comment]
Thanks for finding this. I think it's been fixed. if not, please let me know where you found the link.
